#  Name of workflow
name: Production workflow

# When workflow is triggered
on:
  push:
    branches:
      - master
    tags:
      - "v*"

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      # Run npm install and build on our code
      - run: npm install
      - run: npm run build --if-present
      # Deploy to Netlify using our production secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@375963b92b795c7b979927c580dd6f2a65ebcf28
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.RESPVIS_NETLIFY }}
          NETLIFY_SITE_ID: ${{ secrets.RESPVIS_NETLIFY_MASTER_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["RESPVIS_NETLIFY", "RESPVIS_NETLIFY_MASTER_SITE_ID"]'
