#  Name of workflow
name: Production workflow

# When workflow is triggered
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 18.17
        uses: actions/setup-node@v4
        with:
          node-version: 18.17
      # Run npm install and build on our code
      - run: npm install
      - run: npm run build
      # Deploy self-contained examples to Netlify
      - name: Deploy to netlify
        uses: netlify/actions/cli@375963b92b795c7b979927c580dd6f2a65ebcf28
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.RESPVIS_NETLIFY }}
          NETLIFY_SITE_ID: ${{ secrets.RESPVIS_NETLIFY_MASTER_SITE_ID }}
        with:
          args: deploy --dir=dist --prod
          secrets: '["RESPVIS_NETLIFY", "RESPVIS_NETLIFY_MASTER_SITE_ID"]'
      # Build docs
      - run: npm run build-storybook
      # Deploy docs to Netlify
      - name: Deploy to netlify
        uses: netlify/actions/cli@375963b92b795c7b979927c580dd6f2a65ebcf28
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.RESPVIS_NETLIFY }}
          NETLIFY_SITE_ID: ${{ secrets.RESPVIS_NETLIFY_MASTER_DOCS_SITE_ID }}
        with:
          args: deploy --dir=storybook-static --prod
          secrets: '["RESPVIS_NETLIFY", "RESPVIS_NETLIFY_MASTER_DOCS_SITE_ID"]'
